### ISSUE TITLE
Parsing non R files in R folder

### ISSUE THREAD

**Issue by christophsax** [ropensci-review-tools/srr#18]
I have a file `sysdata.rda` in my R folder (which I guess is fine, per [here](https://r-pkgs.org/data.html)). Thus, I got an `invalid multibyte character in parser` error when `roxygen2::parse_file()` runs:

https://github.com/ropensci-review-tools/srr/blob/a0b285d9093095c67f22808e22e93e4f484b9034/R/report.R#L109

It is easy to fix by going for `.R` files only:

```r
    flist <- list.files (file.path (path, "R"), pattern = "\\.[rR]$", full.names = TRUE)
```

It may make sense to be a bit more verbose in case something fails, e.g.,:

```r
    blocks <- lapply (flist, function (i) try(roxygen2::parse_file (i)))
    failing <- flist[sapply(blocks, inherits, "try-error")]
    if (length(failing) > 0L) {
      stop("parsing problem in: ", paste(failing, collapse = ", "))
    }
```

**Comment by mpadge** [comment]
Would you like to PR that?

**Comment by mpadge** [comment]
Please make sure the [regex pattern](https://github.com/ropensci-review-tools/pkgstats/blob/32cdf3e69fbf4fc574ce3b22538ebf3ad67a6278/R/pkgstats.R#L67-L69) is like this:
``` r
    flist <- normalizePath (list.files (file.path (path, "R"),
                                        full.names = TRUE,
                                        pattern = "\\.(r|R|q|s|S)$"))
```

Those are all of the allowed suffixes - yep, including `".q"`, which exists in a few really old-school packages :astonished:
