### ISSUE TITLE
Missing standards

### ISSUE THREAD

**Issue by schneiderpy** [ropensci-review-tools/srr#33]
Hello @mpadge, I have still issues with "missing standards", which are not missing ...
On my local machine pkgcheck() indicates no issues with missing standards, however, using checks_to_markdown() which results in a file on my github repository indicate three (3) missing standards: EA.1.0, G1.0, and G1.1.
These standards are in the README.rmd file, which I have checked with the srr_report() 
Any idea?
[file172433e925d6.knit.pdf](https://github.com/ropensci-review-tools/srr/files/9864859/file172433e925d6.knit.pdf)

**Comment by mpadge** [comment]
Thanks again @schneiderpy - that one was also very much a :bug: here, through presuming README files are always exactly and only "README.Rmd", but yours is "README.rmd". Your version is of course also entirely valid, and this helped to make the code more robust to any possible forms of naming "rEaDmE.rMd". Thank you!

**Comment by mpadge** [comment]
That also made me realise we had not yet added an [allcontributors section](https://github.com/ropenscilabs/allcontributors) to this repo - now done, and so publically acknowledging your contribution here.

**Comment by schneiderpy** [comment]
Thank you @mpadge for pointing this out and finally fixing my incompetence :) 
pkgcheck() is now passing (after changing .rmd with a new .Rmd file)
