### ISSUE TITLE
Improve documention of essential NULL values to terminate roxygen2 blocks

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/srr#37]
Thanks to @helske via https://github.com/s3alfisc/fwildclusterboot/issues/111

These `NULL`s are critical in defining `roxygen2` "blocks". Without them `roxygen2` just passes straight over, and so doesn't feed anything at all to `srr`, leading to standards not being identified. Can't really catch the absence of null here, because `roxygen2` doesn't catch those, but can definitely improve docs to emphasise the critical importance of terminal `NULL`s.

**Comment by mpadge** [comment]
@s3alfisc Sorry about the confusion in documenting your package. If you have a chance, it'd be helpful if you could look at the commit linked above, and let us know whether that is likely to have been sufficient to have avoided confusion? Alternatively, feel free to suggest other places where we might still improve documentation of the importance of terminal `NULL`s in all blocks. Thanks!

**Comment by s3alfisc** [comment]
Yes, it's very clear! =)
