### ISSUE TITLE
srr tag message

### ISSUE THREAD

**Issue by schneiderpy** [ropensci-review-tools/srr#43]
I'm trying to restore srr tags in my package, however, I'm getting a message for all tags like this (example)
✖ srr-stats-standards.R:10: @srrstatsVerbose is not a known tag.

all srr stats tags have the same "not a known tag" message.
using from Rstudio: built>more>document::devtools

Running on Windows 11

**Comment by mpadge** [comment]
Hi Andreas, you seem to have `@srrVerbose`, which is indeed not a tag. The only [tags allowed](https://docs.ropensci.org/srr/articles/srr-stats.html#roxygen2-tags) are `@srrstats`, `@srrstatsTODO`, and `@srrstatsNA` (all case-sensitive). I'll close this for now, but let me know if you've got any more questions. Thanks, Mark

**Comment by schneiderpy** [comment]
Hi Mark, thank you for your reply. It's not just `@srrVerbose` **all** tags say "not a known tag"

**Comment by mpadge** [comment]
But without any more details I can't really help any further. Maybe they're all invalid tags? Maybe the software doesnt proceed after first invalid tag? Either way, all tags should be are of the 3 valid types.

**Comment by schneiderpy** [comment]
The `@srrVerbose` tag comes from the `srr-stats-standards.R` file. I don't have this tag elsewhere. However, I should notice that I'm trying this locally on my machine (not on github) to get an overview of the remaining `@srrstats` and `@srrstatsTODO`. As far as I remember from the last time this should be possible. I also tryed `roxygen2::roxygenise()` .. nothing happens ...

**Comment by mpadge** [comment]
Oh yeah right, sorry, I forgot about the verbose tag, which is `@srrstatsVerbose`, and not `@srrVerbose`. It defaults to `TRUE`, and needs only to be used if you want to suppress `roxygen2` output.

More generally, I presume you're talking about your `concstats` package? The current GitHub version raises an interesting issue. The only `@srrstats` tags are in tests, one vignette, and `README.rmd` (which should conventionally be `README.Rmd`, by the way). The `roxygen2` package only parses documentation lines of objects/functions defined in `/R`. You currently don't have any of those, and so no output is produced. But this works as expected (run in `concstats` directory):
``` r
srr::srr_stats_roxygen("eda") # dumps stds in R/srr-stats-standards.R
roxygen2::roxygenise() # produces output
```

Note that you need to switch on the roclet by adding to your DESCIPTION:
```
Roxygen: list(markdown = TRUE, roclets = c ("rd", "namespace", "srr::srr_stats_roclet"))
```
One thing that we could probably improve is to more clearly explain that running `roxygenise()` only ever outputs details on standards documented in `/R` code, and not other places like tests, vignettes, source code, or README files.

**Comment by mpadge** [comment]
@schneiderpy The above commit updated the README to more clearly explain the point mentioned above. Thanks for prompting that!
